build:
  nodes:
    analysis:
      dependencies:
        before:
          - composer require --dev johnpbloch/wordpress --no-interaction
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
    tests: true
filter:
  dependency_paths:
    - 'wordpress/'
  excluded_paths:
    - 'vendor/*'
checks:
  php: true
coding_style:
  php:
    indentation:
      general:
        use_tabs: true
    spaces:
      around_operators:
        concatenation: true
        negation: true